"use strict";

export default {
	intro: "../../../js/doc/intro.js",
	bootswatch: "../../../js/doc/bootswatch.js",

	bootswatch_badge: "../../../js/doc/bootswatch_badge.js",
	bootswatch_popover: "../../../js/doc/bootswatch_popover.js",
	bootswatch_tooltip: "../../../js/doc/bootswatch_tooltip.js",

	container: "../../../js/doc/container.js",
	grid: "../../../js/doc/grid.js",
	column: "../../../js/doc/column.js",
	gutter: "../../../js/doc/gutter.js",

	formcontrol: "../../../js/doc/formcontrol.js",
	select: "../../../js/doc/select.js",
	checkradio: "../../../js/doc/checkradio.js",
	range: "../../../js/doc/range.js",
	inputgroup: "../../../js/doc/inputgroup.js",
	floatinglabel: "../../../js/doc/floatinglabel.js",

	button: "../../../js/doc/button.js",
	accordion: "../../../js/doc/accordion.js",
	alert: "../../../js/doc/alert.js",
	badge: "../../../js/doc/badge.js",
	breadcrumb: "../../../js/doc/breadcrumb.js",
	btngroup: "../../../js/doc/btngroup.js",
	card: "../../../js/doc/card.js",
	carousel: "../../../js/doc/carousel.js",
	btnclose: "../../../js/doc/btnclose.js",
	collapse: "../../../js/doc/collapse.js",
	dropdown: "../../../js/doc/dropdown.js",
	listgroup: "../../../js/doc/listgroup.js",
	modal: "../../../js/doc/modal.js",
	tab: "../../../js/doc/tab.js",
	navbar: "../../../js/doc/navbar.js",
	offcanvas: "../../../js/doc/offcanvas.js",
	paging: "../../../js/doc/paging.js",
	placeholder: "../../../js/doc/placeholder.js",
	popover: "../../../js/doc/popover.js",
	progress: "../../../js/doc/progress.js",
	toast: "../../../js/doc/toast.js",
	tooltip: "../../../js/doc/tooltip.js",

	icon: "../../../js/doc/icon.js",
	menu: "../../../js/doc/menu.js",
	toc: "../../../js/doc/toc.js",
	pill: "../../../js/doc/pill.js",
	example: "../../../js/doc/example.js",
	label: "../../../js/doc/label.js",
	msg: "../../../js/doc/msg.js",
	table: "../../../js/doc/table.js",
	layout: "../../../js/doc/layout.js",

	tag_base: "../../../js/doc/tag.base.js",
	tag_text: "../../../js/doc/tag.text.js",
	tag_background: "../../../js/doc/tag.background.js",
	tag_border: "../../../js/doc/tag.border.js",
	tag_color: "../../../js/doc/tag.color.js",
	tag_display: "../../../js/doc/tag.display.js",
	tag_flex: "../../../js/doc/tag.flex.js",
	tag_float: "../../../js/doc/tag.float.js",
	tag_interaction: "../../../js/doc/tag.interaction.js",
	tag_overflow: "../../../js/doc/tag.overflow.js",
	tag_position: "../../../js/doc/tag.position.js",
	tag_shadow: "../../../js/doc/tag.shadow.js",
	tag_size: "../../../js/doc/tag.size.js",
	tag_spacing: "../../../js/doc/tag.spacing.js",
	tag_valign: "../../../js/doc/tag.valign.js",
	tag_visibility: "../../../js/doc/tag.visibility.js",

	tag_ex_a: "../../../js/doc/tag.ex.a.js",
	tag_ex_abbr: "../../../js/doc/tag.ex.abbr.js",
	tag_ex_b: "../../../js/doc/tag.ex.b.js",
	tag_ex_blockquote: "../../../js/doc/tag.ex.blockquote.js",
	tag_ex_cite: "../../../js/doc/tag.ex.cite.js",
	tag_ex_code: "../../../js/doc/tag.ex.code.js",
	tag_ex_div: "../../../js/doc/tag.ex.div.js",
	tag_ex_em: "../../../js/doc/tag.ex.em.js",
	tag_ex_form: "../../../js/doc/tag.ex.form.js",
	tag_ex_footer: "../../../js/doc/tag.ex.footer.js",
	tag_ex_h: "../../../js/doc/tag.ex.h.js",
	tag_ex_hr: "../../../js/doc/tag.ex.hr.js",
	tag_ex_i: "../../../js/doc/tag.ex.i.js",
	tag_ex_img: "../../../js/doc/tag.ex.img.js",
	tag_ex_li: "../../../js/doc/tag.ex.li.js",
	tag_ex_nav: "../../../js/doc/tag.ex.nav.js",
	tag_ex_ol: "../../../js/doc/tag.ex.ol.js",
	tag_ex_p: "../../../js/doc/tag.ex.p.js",
	tag_ex_pre: "../../../js/doc/tag.ex.pre.js",
	tag_ex_small: "../../../js/doc/tag.ex.small.js",
	tag_ex_span: "../../../js/doc/tag.ex.span.js",
	tag_ex_strong: "../../../js/doc/tag.ex.strong.js",
	tag_ex_ul: "../../../js/doc/tag.ex.ul.js",

	generic: "../../../js/doc/generic.js",
	file: "../../../js/doc/file.js",
	query: "../../../js/doc/query.js",
	list: "../../../js/doc/list.js",
	user: "../../../js/doc/user.js",
};
