"use strict";

export default {
	intro: "./doc/intro.js",

	container: "./doc/container.js",
	grid: "./doc/grid.js",
	column: "./doc/column.js",
	gutter: "./doc/gutter.js",

	formcontrol: "./doc/formcontrol.js",
	select: "./doc/select.js",
	checkradio: "./doc/checkradio.js",
	range: "./doc/range.js",
	inputgroup: "./doc/inputgroup.js",
	floatinglabel: "./doc/floatinglabel.js",

	button: "./doc/button.js",
	accordion: "./doc/accordion.js",
	alert: "./doc/alert.js",
	badge: "./doc/badge.js",
	breadcrumb: "./doc/breadcrumb.js",
	btngroup: "./doc/btngroup.js",
	card: "./doc/card.js",
	carousel: "./doc/carousel.js",
	btnclose: "./doc/btnclose.js",
	collapse: "./doc/collapse.js",
	dropdown: "./doc/dropdown.js",
	listgroup: "./doc/listgroup.js",
	modal: "./doc/modal.js",
	tab: "./doc/tab.js",
	navbar: "./doc/navbar.js",
	offcanvas: "./doc/offcanvas.js",
	paging: "./doc/paging.js",
	popover: "./doc/popover.js",
	progress: "./doc/progress.js",
	toast: "./doc/toast.js",
	tooltip: "./doc/tooltip.js",

	icon: "./doc/icon.js",
	menu: "./doc/menu.js",
	toc: "./doc/toc.js",
	pill: "./doc/pill.js",
	example: "./doc/example.js",
	label: "./doc/label.js",
	msg: "./doc/msg.js",
	table: "./doc/table.js",
	layout: "./doc/layout.js",

	tag_base: "./doc/tag.base.js",
	tag_text: "./doc/tag.text.js",
	tag_background: "./doc/tag.background.js",
	tag_border: "./doc/tag.border.js",
	tag_color: "./doc/tag.color.js",
	tag_display: "./doc/tag.display.js",
	tag_flex: "./doc/tag.flex.js",
	tag_float: "./doc/tag.float.js",
	tag_interaction: "./doc/tag.interaction.js",
	tag_overflow: "./doc/tag.overflow.js",
	tag_position: "./doc/tag.position.js",
	tag_shadow: "./doc/tag.shadow.js",
	tag_size: "./doc/tag.size.js",
	tag_spacing: "./doc/tag.spacing.js",
	tag_valign: "./doc/tag.valign.js",
	tag_visibility: "./doc/tag.visibility.js",

	tag_ex_a: "./doc/tag.ex.a.js",
	tag_ex_b: "./doc/tag.ex.b.js",
	tag_ex_code: "./doc/tag.ex.code.js",
	tag_ex_div: "./doc/tag.ex.div.js",
	tag_ex_form: "./doc/tag.ex.form.js",
	tag_ex_h: "./doc/tag.ex.h.js",
	tag_ex_hr: "./doc/tag.ex.hr.js",
	tag_ex_img: "./doc/tag.ex.img.js",
	tag_ex_li: "./doc/tag.ex.li.js",
	tag_ex_nav: "./doc/tag.ex.nav.js",
	tag_ex_ol: "./doc/tag.ex.ol.js",
	tag_ex_p: "./doc/tag.ex.p.js",
	tag_ex_pre: "./doc/tag.ex.pre.js",
	tag_ex_small: "./doc/tag.ex.small.js",
	tag_ex_span: "./doc/tag.ex.span.js",
	tag_ex_strong: "./doc/tag.ex.strong.js",
	tag_ex_ul: "./doc/tag.ex.ul.js",

	generic: "./doc/generic.js",
	file: "./doc/file.js",
	query: "./doc/query.js",
	list: "./doc/list.js",
	user: "./doc/user.js",
};
